import { Poppins} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className={`${poppins.className} min-h-screen`}>
        {children} 
        <Toaster position="top" />
        </body>
    </html>
  );
}
